services:
  webserver:
    environment:
      - POSTGRESQL_URL=${POSTGRESQL_URL}
      - SESSION_KEY=${SESSION_KEY}
      - REL=${REL}
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SENDER=${SMTP_SENDER}
      - APP_BASE_URL=${APP_BASE_URL}
  db:
    image: docker.io/postgres:16-alpine
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

